### ISSUE TITLE
discord notification 

### ISSUE THREAD

**Issue by cristianoronaldosuii** [ScriptNation/ROLLHELPER-public#3]
The Discord webhook notification for deposits is broken and doesn't work for me. it seems like the sendWebHookDiscord function is defined but not called in the code.

**Comment by ScriptNation** [comment]
Hey, yes I forgot about those, seems like the selector for the pop-ups slightly changed with the new UI update, I will update shortly. But I have noticed that sometimes the popup fails to load on the website so that might be issue for some auto-accepts but for now I will update so it should work just like before. Let me know if you encoutner any other issues. Thanks.

**Comment by cristianoronaldosuii** [comment]
Hey there! I just wanted to say that you're doing an amazing job handling these updates and addressing the issues that come up. For the auto-accept, I noticed even when the popup fails to load it automatically clicks on the "Yes, I'm ready" button on the deposit panel. I had 118 deposits with it yesterday it didn't miss one.
